version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - data:/app/data
    networks:
      - app-network
    networks:
      - bot-network

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command:
      '/bin/sh -c ''cp ./nginx/nginx.conf /etc/nginx/nginx.conf; while :; do sleep 6h & wait $${!}; nginx -s reload; done &
      nginx -g "daemon off;"'''
    depends_on:
      - bot
    networks:
      - bot-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint:
      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait
      $${!}; done;'"

networks:
  bot-network:

volumes:
  data:
