version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - data:/app/data
      - ./keys:/app/keys
volumes:
  data:
